### ISSUE TITLE
SCC back-end

### ISSUE THREAD

**Issue by moio** [moio/minima#2]
Implement code in order to download repositories from the SUSE Customer Center.

This will help [sumaform](https://github.com/moio/sumaform) being usable outside of SUSE's VPNs.

Configuration file should contain fields for the SCC credentials and a list of repositories to mirror.

**Comment by juliogonzalez** [comment]
Isn't it this implemented already?

I can see we are using SCC repositories and credentials at sumaform. How is it possible?

**Comment by juliogonzalez** [comment]
It's even at the `README.md` file :-D
